services:
  database:
    image: postgis/postgis:16-3.4
    container_name: evacuapp-postgis
    restart: unless-stopped
    shm_size: '1gb'  # 👈 AUMENTA LA MEMORIA COMPARTIBA DE POSTGIS A 1 GB
    environment:
      POSTGRES_DB: evacuapp
      POSTGRES_USER: evacuapp_user
      POSTGRES_PASSWORD: evacuapp_password
    ports:
      - "15432:5432"
    volumes:
      - postgis_data:/var/lib/postgresql/data
      - ./docker/init-postgis.sql:/docker-entrypoint-initdb.d/init-postgis.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U evacuapp_user -d evacuapp"]
      interval: 5s
      timeout: 5s
      retries: 10

  backend:
    profiles: ["production"]
    build:
      context: .
      dockerfile: Dockerfile
    container_name: evacuapp-backend
    restart: unless-stopped
    depends_on:
      database:
        condition: service_healthy
      ml-service:
        condition: service_started
    environment:
      PORT: 3000
      NODE_ENV: production
      DB_HOST: database
      DB_PORT: 5432
      DB_NAME: evacuapp
      DB_USER: evacuapp_user
      DB_PASSWORD: evacuapp_password
      JWT_SECRET: ${JWT_SECRET:-CAMBIAR_POR_UN_SECRETO_LARGO_Y_ALEATORIO}
      JWT_EXPIRES_IN: 7d
      ML_SERVICE_URL: http://ml-service:8001
    ports:
      - "3000:3000"

  ml-service:
    build: ./ml_service
    container_name: evacuapp-ml
    restart: unless-stopped
    ports:
      - "8001:8001"

  graph-ingestion:
    profiles: ["ingestion"]
    build:
      context: .
      dockerfile: docker/ingestion/Dockerfile
    container_name: evacuapp-graph-ingestion
    depends_on:
      database:
        condition: service_healthy
    environment:
      PGHOST: database
      PGPORT: 5432
      PGDATABASE: evacuapp
      PGUSER: evacuapp_user
      PGPASSWORD: evacuapp_password
      PBF_URL: https://download.geofabrik.de/south-america/chile-latest.osm.pbf
    volumes:
      - ./docker/data:/data

volumes:
  postgis_data: